name: numpedriversapp
description: An application to review the drivers.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  get_storage: ^2.1.1
  cupertino_icons: ^1.0.5
  easy_localization: ^3.0.2
  package_info_plus: ^3.1.2
  flutter_dotenv: ^5.1.0
  wakelock: ^0.6.2
  flutter_launcher_icons: ^0.13.1
  firebase_core: ^2.15.1
  firebase_messaging: ^14.6.7
  cloud_firestore: ^4.9.1
  firebase_crashlytics: ^3.3.5

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon_bg.png"

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/icon/
    - env/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
